name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

#[[d1_databases]]
#binding = "db"			#D1 database binding name (do not change)
#database_name = ""		#D1 database name
#database_id = ""		#D1 database id

#[[kv_namespaces]]
#binding = "kv"			#KV binding name (do not change)
#id = ""				#KV database id

#[[r2_buckets]]
#binding = "r2"			#R2 bucket binding name (do not change)
#bucket_name = ""		#R2 bucket name

#[[send_email]]
#name = "email"			#CF email sending, takes priority when configured

[ai]
binding = "ai"

[assets]
binding = "assets"		#Static assets binding name (do not change)
directory = "./dist"	#Frontend Vue build output directory, default is dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["*/30 * * * *", "0 16 * * *"]	#Refresh analysis cache every 30 min, daily task at midnight


[vars]
#ai_model = ""			#AI model, defaults to @cf/meta/llama-3.1-8b-instruct
#analysis_cache = false	#Enable analysis data caching
#orm_log = false		#Enable SQL logging
#domain = []			#Email domains, supports multiple. Example: ["example1.com","example2.com"]
#admin = ""				#Admin email. Example: admin@example.com
#jwt_secret = ""		#JWT secret key, any random string

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
